export const NAMES = {
  English: [
    "James",
    "Mary",
    "Robert",
    "Patricia",
    "John",
    "Jennifer",
    "Michael",
    "Linda",
    "David",
    "Elizabeth",
    "William",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
  ],
  Spanish: [
    "Alejandro",
    "Sofia",
    "Mateo",
    "Valentina",
    "Santiago",
    "Isabella",
    "Diego",
    "Camila",
    "Gabriel",
    "Lucia",
  ],
  French: [
    "Pierre",
    "Marie",
    "Thomas",
    "Camille",
    "Nicolas",
    "Lea",
    "Julien",
    "Sarah",
    "Lucas",
    "Chloé",
  ],
  German: [
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Meyer",
    "Wagner",
    "Becker",
  ],
  Turkish: [
    "Ahmet",
    "Ayşe",
    "Mehmet",
    "Zeynep",
    "Mustafa",
    "Elif",
    "Can",
    "Fatma",
  ],
  Default: ["Alex", "Sarah", "John", "Emily", "Mike", "Laura", "Steve", "Anna"],
};