export const SCENARIOS = [
  // --- MEVCUT OLANLAR ---
  {
    id: "1",
    title: "Havaalanında Check-in",
    role: "Check-in Görevlisi",
    level: "Orta",
    icon: "flight-takeoff",
  },
  {
    id: "2",
    title: "Kafede Tanışma",
    role: "Müşteri",
    level: "Kolay",
    icon: "local-cafe",
  },
  {
    id: "3",
    title: "İş Görüşmesi",
    role: "İK Müdürü",
    level: "Zor",
    icon: "business-center",
  },
  {
    id: "4",
    title: "Market Alışverişi",
    role: "Kasiyer",
    level: "Kolay",
    icon: "shopping-cart",
  },
  {
    id: "5",
    title: "Restoranda Sipariş Verme",
    role: "Garson",
    level: "Kolay",
    icon: "restaurant",
  },
  {
    id: "6",
    title: "Taksi Çağırma",
    role: "Taksi Şoförü",
    level: "Kolay",
    icon: "local-taxi",
  },

  // --- YENİ EKLENENLER ---
  {
    id: "7",
    title: "Otel Resepsiyonu",
    role: "Resepsiyonist",
    level: "Orta",
    icon: "hotel",
  },
  {
    id: "8",
    title: "Adres Sorma",
    role: "Yerel Halk",
    level: "Kolay",
    icon: "map",
  },
  {
    id: "9",
    title: "Doktor Muayenesi",
    role: "Doktor",
    level: "Zor",
    icon: "medical-services",
  },
  {
    id: "10",
    title: "Kıyafet Alışverişi",
    role: "Mağaza Görevlisi",
    level: "Kolay",
    icon: "checkroom",
  },
  {
    id: "11",
    title: "Polise Kayıp İhbarı",
    role: "Polis Memuru",
    level: "Zor",
    icon: "local-police",
  },
  {
    id: "12",
    title: "Spor Salonu Kaydı",
    role: "Antrenör",
    level: "Orta",
    icon: "fitness-center",
  },
  {
    id: "13",
    title: "Film Hakkında Sohbet",
    role: "Arkadaş",
    level: "Orta",
    icon: "movie",
  },
  {
    id: "14",
    title: "Eczaneden İlaç Alma",
    role: "Eczacı",
    level: "Orta",
    icon: "local-pharmacy",
  },
  {
    id: "15",
    title: "Teknik Destek (İnternet)",
    role: "Müşteri Temsilcisi",
    level: "Zor",
    icon: "router",
  },
  {
    id: "16",
    title: "Kuaför Randevusu",
    role: "Kuaför",
    level: "Kolay",
    icon: "content-cut",
  },
  {
    id: "17",
    title: "Ev Kiralama",
    role: "Emlakçı",
    level: "Zor",
    icon: "home",
  },
  {
    id: "18",
    title: "Tren Bileti Alma",
    role: "Gişe Görevlisi",
    level: "Kolay",
    icon: "train",
  },
  {
    id: "19",
    title: "Kütüphane Üyeliği",
    role: "Kütüphaneci",
    level: "Orta",
    icon: "menu-book",
  },
  {
    id: "20",
    title: "Araba Kiralama",
    role: "Acente Görevlisi",
    level: "Orta",
    icon: "directions-car",
  },
];