export const SCENARIOS = [
  {
    id: "1",
    titleKey: "scenario_airport_checkin",
    roleKey: "role_checkin_agent",
    levelKey: "medium",
    icon: "flight-takeoff",
    isPremium: true,
  },
  {
    id: "2",
    titleKey: "scenario_cafe_meeting",
    roleKey: "role_customer",
    levelKey: "easy",
    icon: "local-cafe",
    isPremium: false,
  },
  {
    id: "3",
    titleKey: "scenario_job_interview",
    roleKey: "role_hr_manager",
    levelKey: "hard",
    icon: "business-center",
    isPremium: true,
  },
  {
    id: "4",
    titleKey: "scenario_grocery_shopping",
    roleKey: "role_cashier",
    levelKey: "easy",
    icon: "shopping-cart",
    isPremium: false,
  },
  {
    id: "5",
    titleKey: "scenario_restaurant_order",
    roleKey: "role_waiter",
    levelKey: "easy",
    icon: "restaurant",
    isPremium: false,
  },
  {
    id: "6",
    titleKey: "scenario_taxi_call",
    roleKey: "role_taxi_driver",
    levelKey: "easy",
    icon: "local-taxi",
    isPremium: false,
  },
  {
    id: "7",
    titleKey: "scenario_hotel_reception",
    roleKey: "role_receptionist",
    levelKey: "medium",
    icon: "hotel",
    isPremium: true,
  },
  {
    id: "8",
    titleKey: "scenario_asking_directions",
    roleKey: "role_local",
    levelKey: "easy",
    icon: "map",
    isPremium: false,
  },
  {
    id: "9",
    titleKey: "scenario_doctor_appointment",
    roleKey: "role_doctor",
    levelKey: "hard",
    icon: "medical-services",
    isPremium: true,
  },
  {
    id: "10",
    titleKey: "scenario_clothes_shopping",
    roleKey: "role_store_clerk",
    levelKey: "easy",
    icon: "checkroom",
    isPremium: false,
  },
  {
    id: "11",
    titleKey: "scenario_police_report",
    roleKey: "role_police_officer",
    levelKey: "hard",
    icon: "local-police",
    isPremium: false,
  },
  {
    id: "12",
    titleKey: "scenario_gym_registration",
    roleKey: "role_trainer",
    levelKey: "medium",
    icon: "fitness-center",
    isPremium: false,
  },
  {
    id: "13",
    titleKey: "scenario_movie_chat",
    roleKey: "role_friend",
    levelKey: "medium",
    icon: "movie",
    isPremium: false,
  },
  {
    id: "14",
    titleKey: "scenario_pharmacy",
    roleKey: "role_pharmacist",
    levelKey: "medium",
    icon: "local-pharmacy",
    isPremium: false,
  },
  {
    id: "15",
    titleKey: "scenario_tech_support",
    roleKey: "role_support_agent",
    levelKey: "hard",
    icon: "router",
    isPremium: true,
  },
  {
    id: "16",
    titleKey: "scenario_hair_salon",
    roleKey: "role_hairdresser",
    levelKey: "easy",
    icon: "content-cut",
    isPremium: false,
  },
  {
    id: "17",
    titleKey: "scenario_house_rental",
    roleKey: "role_realtor",
    levelKey: "hard",
    icon: "home",
    isPremium: true,
  },
  {
    id: "18",
    titleKey: "scenario_train_ticket",
    roleKey: "role_ticket_agent",
    levelKey: "easy",
    icon: "train",
    isPremium: false,
  },
  {
    id: "19",
    titleKey: "scenario_library_membership",
    roleKey: "role_librarian",
    levelKey: "medium",
    icon: "menu-book",
    isPremium: false,
  },
  {
    id: "20",
    titleKey: "scenario_car_rental",
    roleKey: "role_rental_agent",
    levelKey: "medium",
    icon: "directions-car",
    isPremium: false,
  },
];
